export const questions_array_object = [
    {
        question_no: 1,
        question_text: "What was the day of week on 17th June 1998?",
        options:{ a: "Wednesday", b: "Monday", c: "Thursday", d: "Friday" },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 2,
        question_text: "What is mean by test2?",
        options:{ a: 2, b: 1, c: 5, d: 6 },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 3,
        question_text: "What is mean by test2?",
        options:{ a: 2, b: 1, c: 5, d: 6 },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 4,
        question_text: "What was the day of week on 19th June 1998?",
        options:{ a: "Monday", b: "Wednesday", c: "Saturday", d: "Friday" },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 5,
        question_text: "What was the day of week on 1st June 1998?",
        options:{ a: "Thursday", b: "Monday", c: "Wednesday", d: "Friday" },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 6,
        question_text: "What is mean by test6?",
        options:{ a: 8, b: 4, c: 3, d: 87 },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 7,
        question_text: "What is mean by test2? What is mean by test7",
        options:{ a: 8, b: 5, c: 4, d: 5 },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 8,
        question_text: "What was the day of week on 25th June 2005?",
        options:{ a: "Friday", b: "Saturday", c: "Wednesday", d: "Monday"},
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 9,
        question_text: "What was the day of week on 1st May 1998?",
        options:{ a: "Sunday", b: "Monday", c: "Saturday", d: "Friday" },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 10,
        question_text: "What is mean by test10? Coz mean by test10.",
        options:{ a: 58, b: 44, c: 3, d: 87 },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 11,
        question_text: "What is mean by test11? What is mean by test?",
        options:{ a: 228, b: 95, c: 904, d: 50 },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 12,
        question_text: "What was the day of week on 25th June 1900?",
        options:{ a: "Friday", b: "Saturday", c: "Wednesday", d: "Monday"},
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 13,
        question_text: "What is mean by test13? Coz mean by test13.",
        options:{ a: 8, b: 4, c: 3, d: 87 },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 14,
        question_text: "What is mean by test14? What is mean by test14?",
        options:{ a: 8, b: 5, c: 4, d: 5 },
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    },
    {
        question_no: 15,
        question_text: "What will the day of week on 25th June 2020?",
        options:{ a: "Friday", b: "Saturday", c: "Wednesday", d: "Monday"},
        right_answer: "b",
        selected_option: "a",
        mark_review: false,
        save_mark_review: false,
        save: false,
        multiselect: false,
        answer_multiselect:[],
        right_answer_multiselect: [],
        descriptive_answer: false,
        descriptive_rigth_answer: "",
        descriptive_given_answer: ""
    }

];